### ISSUE TITLE
[ipfs/go-bitswap] Conform to licensing policy and link contributing guidelines in README

### ISSUE THREAD

**Issue by Mr0grog** [ipfs/boxo#102]
The license section should make sure to conform to the [IPFS licensing policy](https://github.com/ipfs/community/blob/64d3c9b681ea85b6a4ce90e9ee248efe3b9338a7/docs/licensing-policy.md#attaching-a-license) by linking the actual license file.

We should also make sure to link to the [contributing guidelines](
https://github.com/ipfs/community/blob/master/contributing.md) in the contributing section

Side notes:

- Is it correct that copyright is assigned to @jbenet here and not Protocol Labs, Inc?
- We don’t technically follow standard-readme here (e.g. no usage section, which is required). Should that note in the contributing section change?

**Comment by Jorropo** [comment]
I don't think that is relevent anymore.
