### ISSUE TITLE
More useful html with dag-cbor

### ISSUE THREAD

**Issue by anjor** [ipfs/boxo#307]
I have been working with @linuskendall on onboarding [solana blockchain data to filecoin](https://github.com/rpcpool/yellowstone-faithful). The data is encoded with dag-cbor.

We are thinking of supporting retrievals (backed by Saturn) in an IPFS gateway. The intended UX was similar to what a user gets with a unixfs dag in ipfs gateway — they see directories that they can click into till they get to a file, at which point they can decide to download it.

Unfortunately this doesn’t work with dag-cbor — [relevant slack thread](https://filecoinproject.slack.com/archives/CRLC5H4J0/p1682179609351529) . With Kubo 0.18, it recognises the block as dag-cbor and gives the user a helpful message, however, the user still has to download the block and then decode it themselves. 

![Screenshot 2023-05-15 at 2 34 46 PM](https://github.com/ipfs/boxo/assets/1911631/db1287f5-e619-4bfc-a5ee-33bd706e85c5)

A user should be able to start at the epoch level, and go down the dag to the point where they want to start downloading, and then download everything under — similar to unixfs.

**Comment by anjor** [comment]
Chatted with @lidel @BigLep and @magik6k about this over slack as well, so tagging them in.

**Comment by lidel** [comment]
Thanks for filling this, discussed internally, team has hands full, 
but we will try to make a stab at basic traversal UI next week
(start with something basic, but enough to enable end users to browse the DAG like they can UnixFS directory listings).

**Comment by anjor** [comment]
https://www.notion.so/ecosystem-wg/Triton-Solana-Retrieval-Plan-88bc96f73f9c4693b5d333cc653ca085

**Comment by anjor** [comment]
// copy pasting @magik6k 's comment here:

simply dumping ipld-prime datamodel tree - https://github.com/lotus-web3/dagparts/blob/main/cmd/dataexpl/hnd_view_ipld.go#L77-L235 might work.

@lidel @hacdias i tried looking into this but got a bit stuck.

Will it be as simple as adding Magik's code here -- https://github.com/ipfs/boxo/blob/main/gateway/handler_codec.go ?

(sorry i am not a frontend dev, and am struggling a bit with the go <> html interface here and could use help)

**Comment by lidel** [comment]
@anjor thanks for trying!  I think @hacdias  can take this over for now:
- There is wip refactoring of HTML templates  happening https://github.com/ipfs/boxo/pull/298
  - GUI for browsing CBOR needs to happen on top of that, so makes sense @hacdias does both
- MVP will be a basic UI that allows for traversing links inside DAG-JSON and DAG-CBOR
  - Once this is in place, defining user interface could be iterated on without touching low level stuff
