### ISSUE TITLE
[ipfs/go-bitswap] Use contexts for sessions

### ISSUE THREAD

**Issue by Stebalien** [ipfs/boxo#94]
Instead of creating special sessions, it would be awesome if we could just call:

```
ctx := WithSession(ctx)
```

And get a session that closes when the context is canceled. Then, when making requests, we'd pick the session out of the context. This would make it _much_ easier to thread sessions through ipfs.

**Comment by Jorropo** [comment]
This is now available in 22fa8b16a3e530b86542286bebba77c08e17487e :tada:
